# Generated by Django 4.2.6 on 2023-10-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='Banner')),
                ('http_link', models.URLField(max_length=150)),
                ('ordering', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Banners',
            },
        ),
    ]
