# Generated by Django 4.2.6 on 2023-10-23 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0008_scrapeproduct_scrapeproduct1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapeProduct',
        ),
    ]
